apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: nginx-gitops

  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/DevOps8883/gitops-david.git
    targetRevision: main
    path: manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
<<<<<<< HEAD
                                             
=======
                                             
>>>>>>> c912f888d99f1a027a7e206fd1866d43fa574f5f
